### ISSUE TITLE
Running app locally PUT/POST APIs come as 404

### ISSUE THREAD

**Issue by myaesubi** [johnpapa/shopathome#20]
Hi @johnpapa/@yooakim,
Thanks for the sample work for Static Web App files. 

I'm using it both for honing my skills on Angular as well as working the Static Web App functions.

Running the app locally... all GET HTTP verbs work fine, but PUT/POST returns 404.

not sure, I am missing something in the routing setup. I ran it per instruction though.

Thank you for  help,
Mohammad

**Comment by johnpapa** [comment]
The authorization in this app restricts modifications to those with the role you designate. By default, I made these not allowed. You could remove those in the `routes.json`. For more details, see  [Docs](https://aka.ms/ng20-docs)
