### ISSUE TITLE
Can't Upgrade to Angular v13

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/shopathome#79]
@mgechev Can you take a look at the Angular folder in the main branch, and try running `ng update` on it to get it to v13? When I did this I got all sorts of peer dependency issues with angular packages.

**Comment by mgechev** [comment]
I was not able to reproduce. I ran:

```
$ npm i
$ ng update @angular/core @angular/cli
```

[Here's](https://github.com/johnpapa/shopathome/pull/80) the draft PR with the update.

**Comment by johnpapa** [comment]
thanks
